# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: Contributors
    url: contributors
    weight: 30
  - name: Persons & Groups
    url:
    weight: 50
    identifier: persons
  - name: Musicians
    url: /musician/
    weight: 51
    parent: persons
  - name: Music groups
    url: /music_group/
    weight: 52
    parent: persons
  - name: Solo projects
    url: /solo_project/
    weight: 53
    parent: persons
  - name: Musicologists
    url: /musicologist/
    weight: 54
    parent: persons
  - name: Music
    url: ""
    identifier: Music
    weight: 55
  - name: Genres, Scenes, Traditions
    url: /genre/
    weight: 56
    parent: Music
  - name: Recordings
    url: /recording/
    weight: 56
    parent: Music
  - name: Music Works
    url: /music_work/
    weight: 57
    parent: Music
  - name: Contact & Events
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '/contact'
    weight: 90
    parent: Contact
  - name: Public talks
    url: /event
    weight: 92
    parent: Contact
